# Netlify設定ファイル

[build]
  # ビルドコマンド
  command = "npm run build"
  
  # 公開ディレクトリ
  publish = "build"

# リダイレクト設定（SPAのため）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# manifest.json
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
